import path from 'path';
import fs from 'fs';
import { execFile } from 'child_process';
import ffmpegStaticPath from 'ffmpeg-static';

function getFfmpegPath(): string {
  // Directly search in local node_modules first to bypass Next.js server-side path translation errors (\ROOT)
  const localWinPath = path.join(process.cwd(), 'node_modules', 'ffmpeg-static', 'ffmpeg.exe');
  if (fs.existsSync(localWinPath)) {
    return localWinPath;
  }
  const localUnixPath = path.join(process.cwd(), 'node_modules', 'ffmpeg-static', 'ffmpeg');
  if (fs.existsSync(localUnixPath)) {
    return localUnixPath;
  }
  
  if (ffmpegStaticPath && fs.existsSync(ffmpegStaticPath)) {
    return ffmpegStaticPath;
  }
  
  throw new Error('FFmpeg binary was not found inside ffmpeg-static package.');
}

export async function extractAudio(inputPath: string, outputDir: string): Promise<string> {
  const ffmpegPath = getFfmpegPath();

  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const fileExt = path.extname(inputPath).toLowerCase();
  
  // Supported audio formats that Gemini can process directly without converting:
  const audioExtensions = ['.mp3', '.wav', '.m4a', '.aac', '.flac', '.ogg'];
  if (audioExtensions.includes(fileExt)) {
    console.log(`Input file ${path.basename(inputPath)} is already an audio file. Skipping extraction.`);
    return inputPath;
  }

  const baseName = path.basename(inputPath, fileExt);
  const outputPath = path.join(outputDir, `${baseName}_extracted.mp3`);

  return new Promise((resolve, reject) => {
    // -y: overwrite output files
    // -i: input file path
    // -vn: disable video recording
    // -acodec libmp3lame: convert to mp3
    // -q:a 4: standard variable bitrate (VBR) (~165 kbps) - perfect balance of size & STT clarity
    const args = [
      '-y',
      '-i', inputPath,
      '-vn',
      '-acodec', 'libmp3lame',
      '-q:a', '4',
      outputPath,
    ];

    console.log(`Running FFmpeg: ${ffmpegPath} ${args.join(' ')}`);

    execFile(ffmpegPath, args, (error, stdout, stderr) => {
      if (error) {
        console.error('FFmpeg execution error:', stderr || stdout);
        return reject(new Error(`FFmpeg extraction failed: ${error.message}`));
      }

      console.log('FFmpeg audio extraction completed successfully.');
      if (fs.existsSync(outputPath)) {
        return resolve(outputPath);
      }
      
      reject(new Error('Audio file was not generated by FFmpeg process.'));
    });
  });
}
